### PR TITLE
Remove overridden declarations from rule

### PR DESCRIPTION
**Pull request by kisenka**
Hi Ben!
This is PR adds ability to remove overridden declarations within rule (partly connected with #1). I dropped test with message "should not be responsible for normalising declarations" for obvious reasons and wrote my own :)

### CODE REVIEW

**Comment by ben-eb** [comment]
Hi @kisenka!

First of all, thanks for your contribution. I haven't got around to implementing this yet as I feel it needs a more robust solution. One reason that duplicate declarations exist is because of vendor prefixes, e.g the flexible box model or different gradient syntaxes, the other is two legal values where one is not supported by an older browser, e.g a pixel fallback for a root em value.

I did start some work on this but I am unable to continue it right now due to working on a big (paid) project. I wonder if you would like to help out if I would release an early alpha at some point this week? I think this optimisation needs to be done carefully, which this patch doesn't do just yet. :smile:

**Comment by kisenka** [comment]
I understand your point about fallback for old browsers, but sometimes it's not necessary (maybe more often than you think). What about implementing this feature as option, which will be disabled by default? I don't want to use forked version of cssnano, because it's awesome!

**Comment by kisenka** [comment]
@ben-eb good idea about alpha version on this week! :wink:

**Comment by ben-eb** [comment]
You're right, it isn't always necessary. But let's take a simple example e.g. flexbox generated by autoprefixer:

```css
/* input */
.example {
    display: flex;
}

/* output */
.example {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}
```

So you can see that to support *modern* specs we need a careful implementation so that we don't break cross-browser code. Other minifiers such as csso and clean-css support this feature but not for all declarations, as far as I'm aware.

**Comment by kisenka** [comment]
@ben-eb sorry for delay. You're right, in case of different display values it's critical. How you plan to implement this? White list for such cases?

**Comment by ben-eb** [comment]
My current work only implements a handful of properties by analysing the value and checking if they are valid, with different behaviour for handling fallbacks. I had this working for color and font size values so far (along with a generic implementation).

Ideally we write lots of tests for allowed values and take it from there. But like I mentioned I don't have too much time for this right now so I would need your help. :wink:

**Comment by ben-eb** [comment]
By the way, this is a start of a module we can use to validate CSS property/values.

https://github.com/ben-eb/css-values

**Comment by RyanZim** [comment]
I would tend to be in favor of _at least_ a limited whitelist. One case I ran into with cssnano was:
```
@font-face {
  font-family: "Bitstream Vera Serif Bold";
  src: url("https://mdn.mozillademos.org/files/2468/VeraSeBd.ttf");
}
body {
  font-family: "Bitstream Vera Serif Bold", Arial;
}
body {
  font-family: Arial;
}
```
I expected that postcss-discard-unused would remove the `@font-face`. Instead, I get this: 
```
@font-face {
  font-family: Bitstream Vera Serif Bold;
  src: url(https://mdn.mozillademos.org/files/2468/VeraSeBd.ttf);
}
body {
  font-family: Bitstream Vera Serif Bold,Arial;
  font-family: Arial;
}
```
(beautified for readability)

Of course, this lack of compression has a fair-sized performance impact.

**Pull request closed without merging**
